sudo: false
language: node_js
node_js:
  - "14.15"
branches:
  only:
    - main
    - /^add-.*$/
cache:
  directories:
    - node_modules
before_install:
  # TODO, must configure AWS
  # - yarn build && yarn deploy
  - npm upgrade
install:
  - npm i
script:
  - npm test src
